name: Checks ğŸ•µï¸â€â™‚ï¸

on:
  push:
    paths:
      - roles/**
      - .github/workflows/checks.yml
      - .ansible-lint

env:
  ANSIBLE_FORCE_COLOR: 1

jobs:
  ansible-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ğŸ
        uses: actions/checkout@v3

      - name: Setup Python ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install Dependencies ğŸ“¦
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ansible Lint ğŸ¨
        run: ansible-lint --config-file .ansible-lint --project-dir .
